config/routes.rb
Rails.application.routes.draw do

  devise_for :atletas, :skip => [:registrations]
  devise_for :users

  resources :atletas
  get 'home/index'

  root 'home#index'

end

app/models/atleta.rb
class Atleta < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable


  def name
    "#{self.nombre} #{self.apellidos}"
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  validates :name, presence: true

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  enum role: [:superadmin, :admin, :entrenador]

  after_initialize :set_default_role, :if => :new_record?
  before_create :generate_authentication_token!

  def set_default_role
    self.role ||= :admin
  end

  def generate_authentication_token!
    begin
      self.auth_token = Devise.friendly_token
    end while self.class.exists?(auth_token: auth_token)
  end

  def self.search(params = {})
    users = params[:role].present? ? User.where('role = ?', User.roles[params[:role]]) : User.all
    users
  end

  def name
    "#{self.nombre} #{self.apellido1} #{self.apellido2}"
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit

  before_action :authenticate_user!
  # after_action :verify_authorized

  layout 'admin_lte_2'

  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/atletas_controller.rb
class AtletasController < ApplicationController


  def index
    authorize Atleta
    @atletas = Atleta.all
  end

  def show
    authorize Atleta
    @atleta = Atleta.find(params[:id])

  end

  def new
    authorize Atleta
    @atleta = Atleta.new
  end

  def edit
    authorize Atleta
    @atleta = Atleta.find(params[:id])
  end

  def create
    authorize Atleta
    @atleta = Atleta.new(user_params)

    temporaryPassword = (0...8).map { ('a'..'z').to_a[rand(26)] }.join

    @atleta.password = temporaryPassword
    # @atleta.is_atleta = true

    if @atleta.save
      UserMailer.welcome_email(@atleta).deliver_now
      redirect_to atletas_path, notice: 'El Atleta fue creado satisfactoriamente.'
    else
      render :new
    end
  end

  def update
    authorize Atleta
    @atleta = Atleta.find(params[:id])
    if params[:atleta][:password].blank? && params[:atleta][:password_confirmation].blank?
      params[:atleta].delete(:password)
      params[:atleta].delete(:password_confirmation)
    end

    if @atleta.update_attributes(user_params)
      redirect_to atletas_path, :notice => 'Atleta actualizado.'
    else
      redirect_to atletas_path, :alert => 'No se pudo actualizar el Atleta.'
    end
  end

  def destroy
    authorize Atleta
    atleta = Atleta.find(params[:id])
    atleta.destroy
    redirect_to atletas_path, :notice => 'Atleta eliminado.'
  end

  def generarContrasena
    authorize Atleta
    @atleta = Atleta.find(params[:id])

    temporaryPassword = (0...8).map { ('a'..'z').to_a[rand(26)] }.join
    @atleta.password = temporaryPassword

    if @atleta.save

      UserMailer.forgot_password(@atleta).deliver

      redirect_to atletas_path, :notice => 'Contraseña enviada.'
    else
      redirect_to atletas_path, :notice => @atleta.errors
    end

  end

  private

  def user_params
    params.require(:atleta).permit(:cedula, :nombre, :apellidos, :email)
  end



end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    authorize User
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def title(page_title)
    content_for(:title){ page_title }
    page_title
  end

  def description(page_description)
    content_for(:description){ page_description }
    page_description
  end
end

app/helpers/atletas_helper.rb
module AtletasHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/atletas/_form.html.erb
<%= form_for(@atleta, html: {class: 'form-horizontal',  id: 'atletasForm'}) do |f| %>

    <% if @atleta.errors.any? %>

        <div class="alert alert-danger alert-dismissable">
          <i class="fa fa-ban"></i>
          <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
          <ul>
            <% @atleta.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>

    <% end %>

    <h4 class="page-header">Información General</h4>



    <div class="form-group">
      <%= f.label :cedula, :Cédula, class: 'col-sm-3 control-label' %>
      <div class="col-sm-9">
        <%= f.text_field :cedula, :autofocus => true, class: 'form-control' %>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :first_name, :Nombre, class: 'col-sm-3 control-label' %>
      <div class="col-sm-9">
        <%= f.text_field :nombre, :autofocus => true, class: 'form-control' %>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :apellidos, "Apellidos", class: 'col-sm-3 control-label' %>
      <div class="col-sm-9">
        <%= f.text_field :apellidos, class: 'form-control' %>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :email, 'Correo electr&oacute;nico'.html_safe, class: 'col-sm-3 control-label' %>
      <div class="col-sm-9">
        <%= f.email_field :email, class: 'form-control' %>
      </div>
    </div>

<% end %>

app/views/atletas/edit.html.erb
<% title('Atletas') %>
<% description('Actualizar Información') %>

<div class="box">
  <div class="box-header with-border">
    <div class="btn-toolbar" role="toolbar" aria-label="">
      <a class="btn btn-default" href="<%= atletas_path%>" role="button" title="Regresar"> <i class="fa fa-arrow-left"></i></a>
      <a class="btn btn-primary submit" role="button" title="Guardar"> <i class="fa fa-save"></i> Guardar</a>
      <a class="btn btn-default" href="<%= atletas_path%>" role="button" title="Cancelar"> <i class="fa fa-times"> Cancelar</i></a>
    </div>
  </div><!-- /.box-header -->
  <div class="box-body">
    <div class="row">
      <div class="col-xs-12">
        <%= render 'form' %>
      </div><!-- /.col -->
    </div> <!-- /.row -->
  </div><!-- /.box-body -->
  <div class="box-footer">
    <a class="btn btn-primary submit" role="button" title="Guardar"> <i class="fa fa-save"></i> Guardar</a>
  </div>
</div><!-- /.box -->

app/views/atletas/index.html.erb
<% title('Atletas') %>
<% description('Lista de atletas') %>

<div class="row">
  <div class="col-xs-12">
    <div class="box">
      <div class="box-header">
        <h3 class="box-title">Listado de Atletas</h3>
        <div class="box-tools pull-right">
          <a class="btn btn-sm btn-primary" href="<%= new_atleta_path %>" role="button" title="Nuevo Atleta"> <i class="fa fa-plus"></i> <span class="hidden-xs">Nuevo Atleta</span></a>&nbsp;

        </div>
      </div><!-- /.box-header -->
      <div class="box-body">
        <table id="tableAtletas" class="table table-striped table-bordered" cellspacing="0" width="100%">
          <thead>
          <tr>
            <th>C&eacute;dula</th>
            <th>Nombre</th>
            <th>Equipo</th>
            <th></th>
          </tr>
          </thead>

          <tbody>
          <% @atletas.each do |atleta| %>
              <tr>
                <td><%= atleta.cedula %></td>
                <td><%= link_to atleta.name, atleta_path(atleta) %></td>
                <td> equipo </td>
                <td><%= link_to '<i class="fa fa-edit"></i> Editar'.html_safe, edit_atleta_path(atleta) %>
                  <% if current_user.admin? or current_user.superadmin? %>
                      <%= link_to '<i class="fa fa-remove"></i> Eliminar'.html_safe, atleta_path(atleta), method: :delete, data: {confirm: "Seguro que desea eliminar el caso #{atleta.name}?"} %>

                  <% end %>
                </td>
              </tr>
          <% end %>
          </tbody>
        </table>
      </div><!-- /.box-body -->
    </div><!-- /.box -->
  </div>
</div>

app/views/atletas/new.html.erb
<% title('Atletas') %>
<% description('Registrar Nuevo Atleta') %>

<div class="box">
  <div class="box-header with-border">
    <div class="btn-toolbar" role="toolbar" aria-label="">
      <a class="btn btn-default" href="<%= atletas_path %>" role="button" title="Regresar"> <i class="fa fa-arrow-left"></i></a>
      <a class="btn btn-primary submit" role="button" title="Guardar"> <i class="fa fa-save"></i> Guardar</a>
      <a class="btn btn-default" href="<%= atletas_path %>" role="button" title="Cancelar"> <i class="fa fa-times"> Cancelar</i></a>
    </div>
  </div><!-- /.box-header -->
  <div class="box-body">
    <div class="row">
      <div class="col-xs-12">
        <%= render 'form' %>
      </div><!-- /.col -->
    </div> <!-- /.row -->
  </div><!-- /.box-body -->
  <div class="box-footer">
    <a class="btn btn-primary submit" role="button" title="Guardar"> <i class="fa fa-save"></i> Guardar</a>
  </div>
</div><!-- /.box -->

app/views/atletas/show.html.erb
<% title("Médico #{@atleta.name}") %>
<% description('Detalle del Médico') %>

<div class="box">
  <div class="box-header with-border">
    <div class="btn-toolbar" role="toolbar" aria-label="">
      <a class="btn btn-default" href="<%= atletas_path%>" role="button" title="Regresar"> <i class="fa fa-arrow-left"></i></a>
      <a class="btn btn-default" href="<%= edit_atleta_path(@atleta)%>" role="button" title="Editar Atleta"> <i class="fa fa-edit"></i></a>
    </div>
    <div class="box-tools pull-right">
      1 de <%= @total%>
      <div class="btn-group">
        <button class="btn btn-default btn-sm"><i class="fa fa-chevron-left"></i></button>
        <button class="btn btn-default btn-sm"><i class="fa fa-chevron-right"></i></button>
      </div><!-- /.btn-group -->
    </div><!-- /.pull-right -->
  </div><!-- /.box-header -->
  <div class="box-body">
    <div class="row">
      <div class="col-xs-12">

        <dl class="dl-horizontal">

          <dt>C&eacute;dula</dt>
          <dd><%= @atleta.cedula %></dd>

          <dt>Nombre</dt>
          <dd><%= @atleta.name %></dd>

          <dt>Correo Electr&oacute;nico</dt>
          <dd><%= @atleta.email %></dd>

          <dt>Fecha Nacimiento</dt>
          <dd><%= @atleta.fecha_nacimiento %></dd>

          <dt>Residencia</dt>
          <dd><%= @atleta.residencia%></dd>

          <dt>G&eacute;nero</dt>
          <dd><%= @atleta.genero%></dd>

          <dt>Tel&eacute;fono</dt>
          <dd><%= @atleta.telefono%></dd>

          <dt>Ocupaci&oacute;n</dt>
          <dd><%= @atleta.ocupacion%></dd>

          <dt>Contacto Emergencia</dt>
          <dd><%= @atleta.emergencia_nombre %></dd>

          <dt>Tel&eacute;fono Emergencia</dt>
          <dd><%= @atleta.emergencia_telefono%></dd>

        </dl>
      </div><!-- /.col -->
    </div> <!-- /.row -->
  </div><!-- /.box-body -->
</div><!-- /.box -->

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/_admin_lte_2_header.html.erb
<!-- Main Header -->
<header class="main-header">

  <!-- Logo -->
  <a href="/" class="logo">
    <!-- mini logo for sidebar mini 50x50 pixels -->
    <!-- logo for regular state and mobile devices -->
    <!--<span class="logo-lg"><b>Alex Azo</b>Sports Coaching</span>-->
    <span class="logo-mini"><b>AA</b>SP</span>
    <!-- logo for regular state and mobile devices -->
    <span class="logo-lg"><%= image_tag 'logo.png', height: 48, alt:'Logo' %></span>
  </a>

  <!-- Header Navbar -->
  <nav class="navbar navbar-static-top" role="navigation">
    <!-- Sidebar toggle button-->
    <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
      <span class="sr-only">Toggle navigation</span>
    </a>
    <!-- Navbar Right Menu -->
    <div class="navbar-custom-menu">
      <ul class="nav navbar-nav">
        <!-- Messages: style can be found in dropdown.less-->
        <!--<li class="dropdown messages-menu">-->
          <!--&lt;!&ndash; Menu toggle button &ndash;&gt;-->
          <!--<a href="#" class="dropdown-toggle" data-toggle="dropdown">-->
            <!--<i class="fa fa-envelope-o"></i>-->
            <!--<span class="label label-success">4</span>-->
          <!--</a>-->
          <!--<ul class="dropdown-menu">-->
            <!--<li class="header">You have 4 messages</li>-->
            <!--<li>-->
              <!--&lt;!&ndash; inner menu: contains the messages &ndash;&gt;-->
              <!--<ul class="menu">-->
                <!--<li>&lt;!&ndash; start message &ndash;&gt;-->
                  <!--<a href="#">-->
                    <!--<div class="pull-left">-->
                      <!--&lt;!&ndash; User Image &ndash;&gt;-->
                      <!--<img src="/assets/user2-160x160.jpg" class="img-circle" alt="User Image"/>-->
                    <!--</div>-->
                    <!--&lt;!&ndash; Message title and timestamp &ndash;&gt;-->
                    <!--<h4>-->
                      <!--Support Team-->
                      <!--<small><i class="fa fa-clock-o"></i> 5 mins</small>-->
                    <!--</h4>-->
                    <!--&lt;!&ndash; The message &ndash;&gt;-->
                    <!--<p>Why not buy a new awesome theme?</p>-->
                  <!--</a>-->
                <!--</li>&lt;!&ndash; end message &ndash;&gt;-->
              <!--</ul>&lt;!&ndash; /.menu &ndash;&gt;-->
            <!--</li>-->
            <!--<li class="footer"><a href="#">See All Messages</a></li>-->
          <!--</ul>-->
        <!--</li>&lt;!&ndash; /.messages-menu &ndash;&gt;-->

        <!-- Notifications Menu -->
        <!--<li class="dropdown notifications-menu">-->
          <!--&lt;!&ndash; Menu toggle button &ndash;&gt;-->
          <!--<a href="#" class="dropdown-toggle" data-toggle="dropdown">-->
            <!--<i class="fa fa-bell-o"></i>-->
            <!--<span class="label label-warning">10</span>-->
          <!--</a>-->
          <!--<ul class="dropdown-menu">-->
            <!--<li class="header">You have 10 notifications</li>-->
            <!--<li>-->
              <!--&lt;!&ndash; Inner Menu: contains the notifications &ndash;&gt;-->
              <!--<ul class="menu">-->
                <!--<li>&lt;!&ndash; start notification &ndash;&gt;-->
                  <!--<a href="#">-->
                    <!--<i class="fa fa-users text-aqua"></i> 5 new members joined today-->
                  <!--</a>-->
                <!--</li>&lt;!&ndash; end notification &ndash;&gt;-->
              <!--</ul>-->
            <!--</li>-->
            <!--<li class="footer"><a href="#">View all</a></li>-->
          <!--</ul>-->
        <!--</li>-->
        <!-- Tasks Menu -->
        <!--<li class="dropdown tasks-menu">-->
          <!--&lt;!&ndash; Menu Toggle Button &ndash;&gt;-->
          <!--<a href="#" class="dropdown-toggle" data-toggle="dropdown">-->
            <!--<i class="fa fa-flag-o"></i>-->
            <!--<span class="label label-danger">9</span>-->
          <!--</a>-->
          <!--<ul class="dropdown-menu">-->
            <!--<li class="header">You have 9 tasks</li>-->
            <!--<li>-->
              <!--&lt;!&ndash; Inner menu: contains the tasks &ndash;&gt;-->
              <!--<ul class="menu">-->
                <!--<li>&lt;!&ndash; Task item &ndash;&gt;-->
                  <!--<a href="#">-->
                    <!--&lt;!&ndash; Task title and progress text &ndash;&gt;-->
                    <!--<h3>-->
                      <!--Design some buttons-->
                      <!--<small class="pull-right">20%</small>-->
                    <!--</h3>-->
                    <!--&lt;!&ndash; The progress bar &ndash;&gt;-->
                    <!--<div class="progress xs">-->
                      <!--&lt;!&ndash; Change the css width attribute to simulate progress &ndash;&gt;-->
                      <!--<div class="progress-bar progress-bar-aqua" style="width: 20%" role="progressbar" aria-valuenow="20" aria-valuemin="0" aria-valuemax="100">-->
                        <!--<span class="sr-only">20% Complete</span>-->
                      <!--</div>-->
                    <!--</div>-->
                  <!--</a>-->
                <!--</li>&lt;!&ndash; end task item &ndash;&gt;-->
              <!--</ul>-->
            <!--</li>-->
            <!--<li class="footer">-->
              <!--<a href="#">View all tasks</a>-->
            <!--</li>-->
          <!--</ul>-->
        <!--</li>-->
        <!-- User Account Menu -->
        <li class="dropdown user user-menu">
          <!-- Menu Toggle Button -->
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            <!-- The user image in the navbar-->
            <img src="/assets/user2-160x160.jpg" class="user-image" alt="User Image"/>
            <!-- hidden-xs hides the username on small devices so only the image appears. -->
            <span class="hidden-xs"><%= current_user.name%></span>
          </a>
          <ul class="dropdown-menu">
            <!-- The user image in the menu -->
            <li class="user-header">
              <img src="/assets/user2-160x160.jpg" class="img-circle" alt="User Image" />
              <p>
                <%= current_user.name%>
                <small>Miembro desde <%= l(current_user.created_at, format: '%b. %Y') %></small>
              </p>
            </li>
            <!-- Menu Body -->
            <li class="user-body">
              <div class="col-xs-4 text-center">
                <a href="#"></a>
              </div>
              <div class="col-xs-4 text-center">
                <a href="#"><%= current_user.role.capitalize %></a>
              </div>
              <div class="col-xs-4 text-center">
                <a href="#"></a>
              </div>
            </li>
            <!-- Menu Footer-->
            <li class="user-footer">
              <div class="pull-left">
                <!--<a href="#" class="btn btn-default btn-flat">Profile</a>-->
              </div>
              <div class="pull-right">
                <%= link_to 'Salir', destroy_user_session_path, :method=>'delete', class: 'btn btn-default btn-flat'%>
              </div>
            </li>
          </ul>
        </li>
        <li>
          <a href="#" data-toggle="control-sidebar"><i class="fa fa-gears"></i></a>
        </li>
      </ul>
    </div>
  </nav>
</header>

app/views/layouts/_admin_lte_2_sidebar.html.erb
<!-- Left side column. contains the logo and sidebar -->
<aside class="main-sidebar">

  <!-- sidebar: style can be found in sidebar.less -->
  <section class="sidebar">

    <!-- Sidebar user panel (optional) -->
    <!--<div class="user-panel">-->
    <!--<div class="pull-left image">-->
    <!--<img src="/assets/user2-160x160.jpg" class="img-circle" alt="User Image" />-->
    <!--</div>-->
    <!--<div class="pull-left info">-->
    <!--<p>Alexander Pierce</p>-->
    <!--&lt;!&ndash; Status &ndash;&gt;-->
    <!--<a href="#"><i class="fa fa-circle text-success"></i> Online</a>-->
    <!--</div>-->
    <!--</div>-->

    <!-- search form (Optional) -->
    <!--<form action="#" method="get" class="sidebar-form">-->
    <!--<div class="input-group">-->
    <!--<input type="text" name="q" class="form-control" placeholder="Search..."/>-->
    <!--<span class="input-group-btn">-->
    <!--<button type='submit' name='search' id='search-btn' class="btn btn-flat"><i class="fa fa-search"></i></button>-->
    <!--</span>-->
    <!--</div>-->
    <!--</form>-->
    <!-- /.search form -->

    <!-- Sidebar Menu -->
    <ul class="sidebar-menu">

      <li class="header">Menu</li>
      <!-- Optionally, you can add icons to the links -->
      <li
      <% if controller.controller_name == "home" %> class="active"
      <% end %> ><a href="<%= home_index_path %>"><i class='fa fa-home'></i> <span>Inicio</span></a></li>
      <li  <% if controller.controller_name == "atletas" %> class="active"
           <% end %> ><a href="<%= atletas_path %>"><i class='fa fa-child'></i> <span>Atletas</span></a></li>
      <li><a href="#"><i class='fa fa-calendar'></i> <span>Planes de Entrenamiento</span></a></li>
      <li><a href="#"><i class='fa fa-calendar'></i> <span>Entrenamientos Personales</span></a></li>

      <li class="header">Configuraci&oacute;n</li>
      <li><a href="#"><i class='fa fa-group'></i> <span>Equipos</span></a></li>
      <li><a href="#"><i class='fa fa-user'></i> <span>Usuarios</span></a></li>
      <!--<li><a href="#"><i class='fa fa-link'></i> <span>Another Link</span></a></li>-->
      <!--<li class="treeview">-->
      <!--<a href="#"><i class='fa fa-link'></i> <span>Multilevel</span> <i class="fa fa-angle-left pull-right"></i></a>-->
      <!--<ul class="treeview-menu">-->
      <!--<li><a href="#">Link in level 2</a></li>-->
      <!--<li><a href="#">Link in level 2</a></li>-->
      <!--</ul>-->
      <!--</li>-->

    </ul>
    <!-- /.sidebar-menu -->
  </section>
  <!-- /.sidebar -->
</aside>

app/views/layouts/admin_lte_2_login.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <title>AlexAzo Sports Coaching | Inicio de sesi&oacute;n</title>
  <meta content='width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no' name='viewport'>

  <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" rel="stylesheet" type="text/css" />
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
  <!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
  <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
  <![endif]-->
  <%= csrf_meta_tags %>
</head>
<body class="login-page">
<div class="login-box">
  <div class="login-logo">
    <span class="logo-lg"><%= image_tag 'logo.png', height: 150, alt:'Logo' %></span>
  </div><!-- /.login-logo -->
  <div class="login-box-body">
    <p class="login-box-msg">Iniciar sesi&oacute;n</p>
    <%= form_for(resource, as: resource_name, url: session_path(resource_name)) do |f| %>
      <div class="form-group has-feedback">
        <%= f.text_field :email, class: 'form-control', autofocus: true %>
        <span class="glyphicon glyphicon-envelope form-control-feedback"></span>
      </div>

      <div class="form-group has-feedback">
        <%= f.password_field :password, class: 'form-control', autocomplete: 'off' %>
        <span class="glyphicon glyphicon-lock form-control-feedback"></span>
      </div>
      <div class="row">
        <div class="col-xs-8">
          <div class="checkbox icheck">
            <label>
              <input type="checkbox"> Recordarme
            </label>
          </div>
        </div><!-- /.col -->
        <div class="col-xs-4">
          <%= f.submit 'Entrar', class: 'btn btn-primary btn-block btn-flat' %>

        </div><!-- /.col -->
      </div>

    <% end %>
  </div><!-- /.login-box-body -->
</div><!-- /.login-box -->

<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Sports Coaching</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>